version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dsw-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vapor
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password_here}
      POSTGRES_DB: dsw_timetable
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vapor"]
      interval: 10s
      timeout: 5s
      retries: 5

  vapor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsw-vapor
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Runtime mode
      ENV: ${ENV:-production}

      # Backend mode: "live" or "cached"
      DSW_BACKEND_MODE: ${DSW_BACKEND_MODE:-cached}

      # Default semester dates
      DSW_DEFAULT_FROM: ${DSW_DEFAULT_FROM:-2025-09-06}
      DSW_DEFAULT_TO: ${DSW_DEFAULT_TO:-2026-02-08}
      DSW_DEFAULT_INTERVAL: ${DSW_DEFAULT_INTERVAL:-semester}

      # Cache TTLs (seconds)
      DSW_TTL_SCHEDULE_SECS: ${DSW_TTL_SCHEDULE_SECS:-60}
      DSW_TTL_SEARCH_SECS: ${DSW_TTL_SEARCH_SECS:-259200}
      DSW_TTL_AGGREGATE_SECS: ${DSW_TTL_AGGREGATE_SECS:-18000}
      DSW_TTL_TEACHER_SECS: ${DSW_TTL_TEACHER_SECS:-18000}

      # Database connection
      DATABASE_URL: postgres://vapor:${POSTGRES_PASSWORD:-your_password_here}@postgres:5432/dsw_timetable
    ports:
      - "8080:8080"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

volumes:
  postgres_data:
    driver: local
